---
- name: Connection tests for Windows hosts
  hosts: all
  gather_facts: false
  roles:
  - role: socks-tunnel-role
    run-once: true
    delegate_to: localhost
  tasks:
    - name: Ping
      win_ping:
