- name: Connection tests for UNIX hosts
  hosts: all
  ignore_errors: true
  tasks:
    - ping:

    - name: Set the current job_id for hosts
      set_stats:
        data:
          log_job_id: "{{ tower_job_id }}"
        aggregate: false
