- name: Connection tests for UNIX hosts
  hosts: all
  ignore_errors: true
  tasks:
    - ping:
    - debug:
        var: tower_job_id
    - name: Set current job_id as stat
      set_fact:
          log_job_id: "{{ tower_job_id }}"
    - debug:
        var: log_job_id
