- name: Connection tests for UNIX hosts
  hosts: all
  ignore_errors: true
  tasks:
    - ping:
    - name: Set current job_id as stat
      set_stats:
        data:
          log_job_id: "{{ tower_job_id }}"
        per_host: true
