- name: Connection tests for UNIX hosts
  hosts: all
  ignore_errors: true
  tasks:
    - ping:
      register: log_result

    - name: Set the current job_id for hosts
      set_stats:
        data:
          log_job_id: "{{ tower_job_id }}"
        aggregate: false
    
    - name: include slack-report role
      include_role:
        name: slack-report
